VERSION="2.2.0"
NETWORK_PASSPHRASE = "Public Global Stellar Network ; September 2015"

[DOCUMENTATION]
ORG_NAME="NFTShopping"
ORG_URL="https://nftshopping.github.io/"
ORG_DESCRIPTION="NFTShopping is a marketplace dedicated to buying, selling, and trading non-fungible tokens (NFTs). NFTs are unique digital assets that represent ownership of a digital or physical item, such as artwork, music, or collectibles."

[[CURRENCIES]]
code="NFT"
issuer="GB3AJUM7TJSIPSEZ2XZYKOAPIW6YH4I6L7S4JRHJK2QZ3HX2CYHCOV4N"
status="live"
display_decimals=7
name="non-fungible token"
desc="At NFTShopping, users can browse a diverse selection of NFTs from various creators and artists, and purchase them using cryptocurrency. Sellers can also list their NFTs for sale on the platform and connect with a global community of buyers."
conditions="provide future benefits"
image="https://nftshopping.github.io/images/NFT.PNG"
